### ISSUE TITLE
[Feature Request] Download free tracks when available

### ISSUE THREAD

**Issue by candroid-man** [Ovyerus/bandsnatch#16]
This would require a lot of work probably, but I noticed that some artists on Bandcamp charge money for the full album, however each individual track in the album is set to "name your price" as shown below:

![image](https://github.com/user-attachments/assets/80d585b9-91bf-4bc4-afcb-f6cbace78f34)

It would be very handy if bandsnatch could automatically download each individual track from an album if the tracks are free. If this is out of scope, feel free to close this.

**Comment by Ovyerus** [comment]
This is out of scope for Bandsnatch, it's just for downloading a user's collection. But also, this would require connecting to the user's email to catch the download links Bandcamp sends, and that's a rabbit hole I don't want to go down.

**Comment by candroid-man** [comment]
Thanks for the reply, and also thank you for this tool it has been very helpful!
