### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by bangcrash** [Ovyerus/bandsnatch#8]
I have downloaded to Linux Mint 21.2, I have made the file executable, created a cookies.json file containing the bandcamp.com cookie and I am using the following command:

`./bandsnatch run -f flac <username>`

After running that command I get:

```
thread 'main' panicked at 'Failed to deserialise collection page data blob.: Error("invalid type: null, expected u16", line: 1, column: 68813)', src/api/mod.rs:76:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Please can you help?

**Comment by patrickkelso** [comment]
I have the same issue, running with RUST_BACKTRACE=full I get this:
`thread 'main' panicked at 'Failed to deserialise collection page data blob.: Error("invalid type: null, expected u16", line: 1, column: 63632)', src/api/mod.rs:76:14
stack backtrace:
   0:     0x55a3e19565a1 - <unknown>
   1:     0x55a3e198187f - <unknown>
   2:     0x55a3e1952d99 - <unknown>
   3:     0x55a3e19563b5 - <unknown>
   4:     0x55a3e19578e3 - <unknown>
   5:     0x55a3e1957674 - <unknown>
   6:     0x55a3e1957e69 - <unknown>
   7:     0x55a3e1957d67 - <unknown>
   8:     0x55a3e1956a06 - <unknown>
   9:     0x55a3e1957ab2 - <unknown>
  10:     0x55a3e1465d33 - <unknown>
  11:     0x55a3e14661d3 - <unknown>
  12:     0x55a3e1495357 - <unknown>
  13:     0x55a3e1490b6e - <unknown>
  14:     0x55a3e1474884 - <unknown>
  15:     0x55a3e14d1c42 - <unknown>
  16:     0x55a3e14b89d7 - <unknown>
  17:     0x55a3e146df23 - <unknown>
  18:     0x55a3e146e2a9 - <unknown>
  19:     0x55a3e194d61b - <unknown>
  20:     0x55a3e14b8ac5 - <unknown>
  21:     0x7f04e8832cd0 - <unknown>
  22:     0x7f04e8832d8a - __libc_start_main
  23:     0x55a3e1466495 - <unknown>
  24:                0x0 - <unknown>`

**Comment by Ovyerus** [comment]
Not able to reproduce this myself :/.

I've released [0.3.0](https://github.com/Ovyerus/bandsnatch/releases/tag/v0.3.0) with a new `debug-collection` subcommand. Could you put the output from `bandsnatch debug-collection --user ...` in here so I can try to understand the cause of the problem?

**Comment by bangcrash** [comment]
I have just downloaded 0.3.0 and it downloads as an archive file type and I'm not able to extract it or open it.  Am I doing something wrong?

**Comment by Ovyerus** [comment]
Sorry about that, looks like the binaries for Linux got uploaded from CI as TAR files without an extension. I did fiddle with CI a bit so I guess I broke something, I'll look into that.

**Comment by Ovyerus** [comment]
CI has been fixed & the 0.3.0 release now has the correct files attached.

**Comment by bangcrash** [comment]
Here you go, this is the output:

`{
  "collection_data": {
    "batch_size": 20,
    "collectors": {},
    "hidden_items_count": 0,
    "item_count": 179,
    "last_token": "1685865736:4116353746:a::",
    "pending_sequence": "[redacted by bandsnatch]",
    "purchase_infos": {},
    "redownload_urls": "[redacted by bandsnatch]",
    "sequence": "[redacted by bandsnatch]",
    "small_collection": false,
    "small_wishlist": true
  },
  "fan_data": {
    "bio": "",
    "fan_id": 6057567,
    "fav_genre": "Metal",
    "followers_count": 6,
    "following_bands_count": 153,
    "following_fans_count": 5,
    "following_genres_count": 22,
    "is_own_page": null,
    "location": "Cambridge, UK",
    "name": "bangcrash",
    "photo": {
      "height": 175,
      "image_id": 24496231,
      "width": 175
    },
    "raw_location": "Cambridge, UK",
    "subscriptions_count": 0,
    "trackpipe_url": "https://bandcamp.com/bangcrash",
    "username": "bangcrash",
    "website_url": ""
  },
  "hidden_data": {
    "batch_size": 20,
    "item_count": null,
    "last_token": null,
    "last_token_is_gift_given": null,
    "pending_sequence": "[redacted by bandsnatch]",
    "sequence": "[redacted by bandsnatch]"
  }
}
`

**Comment by Ovyerus** [comment]
Thanks for that, [0.3.1](https://github.com/Ovyerus/bandsnatch/releases/tag/v0.3.1) should contain a fix for that. Let me know how it goes.

**Comment by bangcrash** [comment]
That's loads better, thank you.

I did get some errors, can they be safely ignored?

./bandsnatch run -f flac bangcrash --dry-run

Fetching information for 179 found releases

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `downloads`", line: 1, column: 4112)', src/api/mod.rs:195:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Failed to get item info for https://bandcamp.com/download?from=collection&payment_id=438349017&sig=50e055bc509e2bbc5690f8b75188e450&sitem_id=146184731.
Run with `--debug` to see the full JSON blob.

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `downloads`", line: 1, column: 3723)', src/api/mod.rs:195:74
Failed to get item info for https://bandcamp.com/download?from=collection&payment_id=2273830387&sig=3d74527f83be73c05c609fe1646ba3bb&sitem_id=261807509.
Run with `--debug` to see the full JSON blob.

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `downloads`", line: 1, column: 4169)', src/api/mod.rs:195:74
Failed to get item info for https://bandcamp.com/download?from=collection&payment_id=382946320&sig=ff2be8287d9b95d78100d3037c9c7f94&sitem_id=255892892.
Run with `--debug` to see the full JSON blob.
`

**Comment by Ovyerus** [comment]
If you run it to download without doing a dry run it should download most just fine. That just means that it's skipping over some items due to something wrong in the data for. I'll take a look into what's causing that issue.

**Comment by bangcrash** [comment]
I've run it now and it seems to be working perfectly.  Thanks very much for fixing this.

**Comment by Ovyerus** [comment]
Glad to hear!

**Comment by patrickkelso** [comment]
Confirming all sorted for me too. Thank you for your work.
